_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

# Step corresponds to patch (because we do batch size 1)
min_steps: 10
max_steps: 100

accelerator: cpu
devices: 1

log_every_n_steps: 1
check_val_every_n_epoch: 1  # Whether to check validation split after every epoch
accumulate_grad_batches: 1 # Accumulates grads every k batches (enables larger effective batch size)
val_check_interval: 1.0 # How often within one training epoch to check the validation set

# Setting to overfit on training (debugging)
overfit_batches: 0.0 # Uses only this fraction/ num_samples per batch for training
limit_val_batches: 1.0 # Disable validation with 0.0
num_sanity_val_steps: 2 # Disable validation sanity checks with 0.0