# @package _global_

defaults:
  - _self_
  - data: pairs
  - model: translation
  - callbacks: default
  - trainer: gpu
  - paths: default
  - hydra: default
  - wandb: default
  - extras: default

task_name: "train"
tags: ["dev"]
seed: null
train: true
test: true